// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	bike "go-zero-demo/api/rpc_demo/internal/handler/bike"
	user "go-zero-demo/api/rpc_demo/internal/handler/user"
	"go-zero-demo/api/rpc_demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TestMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/info",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/rpc/user/info",
					Handler: user.RpcUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/dev/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bike/info",
				Handler: bike.BikeInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bike/insert",
				Handler: bike.BikeInsertHandler(serverCtx),
			},
		},
		rest.WithPrefix("/dev/v1"),
	)
}
