// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcUserServiceClient is the client API for RpcUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcUserServiceClient interface {
	RpcGetUserInfo(ctx context.Context, in *GetUserInfoRes, opts ...grpc.CallOption) (*GetUserInfoReq, error)
}

type rpcUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcUserServiceClient(cc grpc.ClientConnInterface) RpcUserServiceClient {
	return &rpcUserServiceClient{cc}
}

func (c *rpcUserServiceClient) RpcGetUserInfo(ctx context.Context, in *GetUserInfoRes, opts ...grpc.CallOption) (*GetUserInfoReq, error) {
	out := new(GetUserInfoReq)
	err := c.cc.Invoke(ctx, "/pb.RpcUserService/RpcGetUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcUserServiceServer is the server API for RpcUserService service.
// All implementations must embed UnimplementedRpcUserServiceServer
// for forward compatibility
type RpcUserServiceServer interface {
	RpcGetUserInfo(context.Context, *GetUserInfoRes) (*GetUserInfoReq, error)
	mustEmbedUnimplementedRpcUserServiceServer()
}

// UnimplementedRpcUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRpcUserServiceServer struct {
}

func (UnimplementedRpcUserServiceServer) RpcGetUserInfo(context.Context, *GetUserInfoRes) (*GetUserInfoReq, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RpcGetUserInfo not implemented")
}
func (UnimplementedRpcUserServiceServer) mustEmbedUnimplementedRpcUserServiceServer() {}

// UnsafeRpcUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcUserServiceServer will
// result in compilation errors.
type UnsafeRpcUserServiceServer interface {
	mustEmbedUnimplementedRpcUserServiceServer()
}

func RegisterRpcUserServiceServer(s grpc.ServiceRegistrar, srv RpcUserServiceServer) {
	s.RegisterService(&RpcUserService_ServiceDesc, srv)
}

func _RpcUserService_RpcGetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcUserServiceServer).RpcGetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.RpcUserService/RpcGetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcUserServiceServer).RpcGetUserInfo(ctx, req.(*GetUserInfoRes))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcUserService_ServiceDesc is the grpc.ServiceDesc for RpcUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RpcUserService",
	HandlerType: (*RpcUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcGetUserInfo",
			Handler:    _RpcUserService_RpcGetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
