// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"go-zero-demo/pd/rpc_demo/internal/logic"
	"go-zero-demo/pd/rpc_demo/internal/svc"
	"go-zero-demo/pd/rpc_demo/pb"
)

type RpcUserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRpcUserServiceServer
}

func NewRpcUserServiceServer(svcCtx *svc.ServiceContext) *RpcUserServiceServer {
	return &RpcUserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcUserServiceServer) RpcGetUserInfo(ctx context.Context, in *pb.GetUserInfoRes) (*pb.GetUserInfoReq, error) {
	l := logic.NewRpcGetUserInfoLogic(ctx, s.svcCtx)
	return l.RpcGetUserInfo(in)
}
