// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRes struct {
	UserId int `json:"userId" validate:"gte=30,lte=100"` // validate参数校验
}

type UserInfoReq struct {
	UserId int    `json:"userId"`
	Name   string `json:"name"`
}

type BikeInfoRes struct {
	BikeId int `form:"bikeId"` //get请求url传参数
}

type BikeInfoReq struct {
	BikeId   int    `json:"bikeId"`
	BikeName string `json:"bikeName"`
}

type Res struct {
	State     string `json:"state"`
	StateInfo string `json:"stateInfo"`
}
